# Generated by Django 5.0.11 on 2025-02-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="featured_images/"
            ),
        ),
    ]
