# Generated by Django 5.0.11 on 2025-02-15 02:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="featured_images/",
                validators=[blog.models.validate_image_max_size],
            ),
        ),
    ]
