# Generated by Django 5.0.11 on 2025-03-04 22:55

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_post_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags. 3 max.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
