name: Lint with Ruff

on:
  push:
    branches: ["html-for-prod"]
  pull_request:
    branches: ["html-for-prod"]

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latest version of ruff
<<<<<<< HEAD
<<<<<<< HEAD
        uses: astral-sh/ruff-action@v4.1.0
=======
        uses: astral-sh/ruff-action@v4
>>>>>>> 5a26e94 (v4 ruff)
=======
        uses: astral-sh/ruff-action@v4.1.0
>>>>>>> cc78759 (v4 ruff)
        with:
          version: "latest"
          args: "--version"

      - name: Run Ruff Linter
        run: ruff check --fix --unsafe-fixes

      - name: Run Ruff Formatter
        run: ruff format

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Ruff linting and formatting"
